GET http://localhost:3001/todos

###

POST http://localhost:3001/todos/new
Content-Type: application/json

{
    "text" : "order burgers"
}

###

POST http://localhost:3001/todos/delete/624bc5db0483d3bf42e131cd


###


GET http://localhost:3001/todos/complete/6243f1bac9b674fd2482a40d



###
PUT http://localhost:3001/todos/complete/6243f1bac9b674fd2482a40d

{
"text": "Go get chocolates"
}