GET http://localhost:3001/todos

###

POST http://localhost:3001/todos/new
Content-Type: application/json

{
    "text" : "order burger"
}

###

DELETE http://localhost:3001/todos/delete/6241a5056c93fe49b589cd86

###


GET http://localhost:3001/todo/complete/6241a5056c93fe49b589cd86



###
PUT http://localhost:3001/todos/complete/6241bb62e76c0b08e108131e Content-Type : application/json

{
"text": "Go get chocolates"
}